### ISSUE TITLE
怎样转成onnx或者trt呢？

### ISSUE THREAD

**Issue by wwzh2015** [TripleCoenzyme/ResNet50-Unet#5]

**Comment by TripleCoenzyme** [comment]
请仿照[pytorch官方介绍](https://pytorch.org/docs/stable/onnx.html)进行尝试。根据我之前使用onnx的经验，这个网络中所用到的所有操作应该都能够被最新版本的onnx所支持，然后可能可以通过onnx的API转化成TensorRT可用的模型。

此外我使用过一种利用torchscript固定计算图的加速方法，如[这里](https://pytorch.org/tutorials/prototype/torchscript_freezing.html)所示，虽然可能加速效率不如使用onnx的情况，但实现起来相对简单，并且在同结构网络下做过测试。

希望对你有所帮助 : )
